### ISSUE TITLE
Horas pendientes en DB

### ISSUE THREAD

**Issue by ParticleDuality** [SecureInformationCompany/SIC#1]
La cuestión es cómo poner las "horas pendientes" de instructor en la base de datos, es necesario?

**Comment by Julieth27** [comment]
ummm pues creo que habíamos dicho al inicio que lo de las horas pendientes que eso lo haría como automáticamente el programa, ya que los instructores tienen que completar 40 horas pues si le hace falta horas el sistema le informa que le faltan x horas para completar la franja horaria del isntructor

**Comment by ParticleDuality** [comment]
Entonces quedamos que esa funcionalidad no se va a implementar.
